linux: Fix aarch64 build failure due to missing i40e man pages
Building linux.spec on aarch64 fails with the following rpmbuild
errors:

Processing files: linux-docs-4.19.127-1.ph3.aarch64
error: File not found: /usr/src/photon/BUILDROOT/linux-4.19.127-1.ph3.aarch64/usr/share/man/*

RPM build errors:
    File not found: /usr/src/photon/BUILDROOT/linux-4.19.127-1.ph3.aarch64/usr/share/man/*


This is because the man pages were added for the out-of-tree Intel
i40e driver, which is x86_64 only. Fix it by making the man pages
conditional on x86_64.

Change-Id: I44d42224df8fa7545c2bd87a139b748c7b4907e9
Signed-off-by: Srivatsa S. Bhat (VMware) <srivatsa@csail.mit.edu>
Reviewed-on: http://photon-jenkins.eng.vmware.com:8082/10399
Tested-by: gerrit-photon <photon-checkins@vmware.com>
Reviewed-by: Him Kalyan Bordoloi <bordoloih@vmware.com>