linux-esx: Fix bogus date in changelog
Building linux-esx fails with this error message:

"Analyzing SPECS/linux/linux-esx.spec ...
 ERROR in SPECS/linux/linux-esx.spec: bogus date Oct 08 2020 found -
 actual day is Thu, but found Wed"

Fix the day in the changelog. No need to increment release number,
since this is not a functional change.

Change-Id: Ibc66a6fd76a9db3149fef21f86773c831569d86e
Signed-off-by: Srivatsa S. Bhat (VMware) <srivatsa@csail.mit.edu>
Reviewed-on: http://photon-jenkins.eng.vmware.com:8082/11591
Tested-by: gerrit-photon <photon-checkins@vmware.com>
Reviewed-by: ashwin h <ashwinh@vmware.com>